version: "3.8"

services:
  compute:
    build:
      context: .
    hostname: "dev"
    ports:
      - 10022:22
      - 8501:8501
      - 8888:8888
    volumes:
      - .:/opt/project
    privileged: true
    ipc: host
    tty: true
