version: "3.8"

services:
  compute:
    build:
      context: .
    hostname: "dev"
    ports:
      - 8501:8501
    volumes:
      - .:/app
    working_dir: /app
    privileged: true
    ipc: host
    tty: true
